@startuml
start
:Инициализация MPI;

repeat

    :Ввести размер системы N;

    :Сгенерировать случайную матрицу и вектор;
    :Передать матрицу и вектор всем процессам (MPI_Bcast);
    :Инициализация вектора решения;

    repeat
        :Замерить время начала (MPI_Wtime);
        :Распределение строк между процессами;
        :Выполнить метод Зейделя;
        :Обмен результатами (MPI_Allgather);
        :Проверка сходимости;
        :Замерить время конца (MPI_Wtime);
        :Сохранить время выполнения;
    repeat while (Количество запусков < 100)
        
    :Вычислить и вывести результат и среднее время выполнения;

repeat while (Не будет присвоен 0 полю N)

stop
@enduml
