@startuml
start

:Запрос количества потоков;
:Ввод размера массива;

while (Размер массива != 0?) is (нет)
    :Инициализация массива случайными числами;
    :Подсчет времени сортировки;

    fork
        :Разделение массива на блоки;
        :Параллельная сортировка блоков;
    fork again
        :Объединение отсортированных блоков;
    end fork

    :Подсчет среднего времени после 100 тестов;
    :Вывод среднего времени на экран;
    :Запрос нового размера массива;
endwhile (да)
:Запрос нового количества потоков;

stop
@enduml
