@startuml
start

:Инициализация MPI;
:Получение rank и size;
:Инициализация N = 1;
while (N != 0) 
    :Главный процесс (rank 0) инициализирует матрицы A и B;

    :Начало подсчета времени выполнения;

    :Все процессы получают матрицу B с помощью MPI_Bcast;
    :Матрица A рассылается всем процессам через MPI_Scatter;
    :Умножение подматрицы;
    :Результаты подматрицы C собираются через MPI_Gather;
    
    :Подсчет и вывод времени выполнения через MPI_Wtime;

    :Запрос размера матрицы N;
endwhile

:Завершение работы MPI;

stop
@enduml
